"""UFCPS simulation package.

The package provides deterministic reference simulations for testing
carrier-independent procedural continuity.
"""

from .core import (
    CapabilityProfile,
    Carrier,
    CarrierStatus,
    ContinuationState,
    DeadlockState,
    EventType,
    ExecutionResult,
    LocalExecutor,
    Operation,
    ProceduralState,
    ProcessSnapshot,
    RuntimeConfig,
    RuntimeInvariantError,
    SessionStatus,
    SharedStateStore,
    SimulationEvent,
    StateAlreadyExistsError,
    StateNotFoundError,
    StateRecord,
    StateStoreError,
    Transition,
    TransitionType,
    UFCPSExecutionEngine,
    UFCPSExecutionError,
    UFCPSRuntime,
)

from .policies import (
    Candidate,
    CapabilityMatchedPolicy,
    CarrierSelectionError,
    CarrierSelectionPolicy,
    ExplicitOrderPolicy,
    FailureEvent,
    FailureInjectionError,
    FailureInjector,
    FailureType,
    FirstCompatiblePolicy,
    LeastLoadedPolicy,
    available_carriers,
    forced_deadlock,
    selection_candidates,
    single_carrier_failure,
)

from .scenarios import (
    AutonomousExperimentPlan,
    AutonomousExperimentResult,
    ParallelScenarioResult,
    ScenarioResult,
    execute_autonomous_experiment,
    generate_experiment,
    run_autonomous_experiment,
    run_basic_handoff,
    run_parallel_resolution,
)

__all__ = [
    "AutonomousExperimentPlan",
    "AutonomousExperimentResult",
    "Candidate",
    "CapabilityMatchedPolicy",
    "CapabilityProfile",
    "Carrier",
    "CarrierSelectionError",
    "CarrierSelectionPolicy",
    "CarrierStatus",
    "ContinuationState",
    "DeadlockState",
    "EventType",
    "ExecutionResult",
    "ExplicitOrderPolicy",
    "FailureEvent",
    "FailureInjectionError",
    "FailureInjector",
    "FailureType",
    "FirstCompatiblePolicy",
    "LeastLoadedPolicy",
    "LocalExecutor",
    "Operation",
    "ParallelScenarioResult",
    "ProceduralState",
    "ProcessSnapshot",
    "RuntimeConfig",
    "RuntimeInvariantError",
    "ScenarioResult",
    "SessionStatus",
    "SharedStateStore",
    "SimulationEvent",
    "StateAlreadyExistsError",
    "StateNotFoundError",
    "StateRecord",
    "StateStoreError",
    "Transition",
    "TransitionType",
    "UFCPSExecutionEngine",
    "UFCPSExecutionError",
    "UFCPSRuntime",
    "available_carriers",
    "execute_autonomous_experiment",
    "forced_deadlock",
    "generate_experiment",
    "run_autonomous_experiment",
    "run_basic_handoff",
    "run_parallel_resolution",
    "selection_candidates",
    "single_carrier_failure",
]
